### ISSUE TITLE
transaction returned with failure: Error: You've asked to invoke a function that does not exist: initLedger

### ISSUE THREAD

**Issue by crashiers** [matematika-org/matematika.org#1]
transaction returned with failure: Error: You've asked to invoke a function that does not exist: initLedger “”     How to deal with？

**Comment by matematika-org** [comment]
For js and typescript chaincode, you can run InitLedger (capital I) not initLedger. 
I spent 3 or 4 hours to find this mistake in official doc.
If you will have any additional question, you can ask in the telegram chat. 
https://t.me/matematika_eng
